version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - "4306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      #- ./docker/db/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: company_directory
      MYSQL_DATABASE: company_directory
      MYSQL_USER: company_directory
      MYSQL_PASSWORD: company_directory
      TZ: 'Asia/Tokyo'

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  web:
    build: ./docker/web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      #- ./docker/web/log:/var/log/apache2
    container_name: company_directory